apiVersion: v2
name: argocd-wrapper
description: A wrapper chart for ArgoCD with custom configuration
type: application
version: 0.1.0
appVersion: "2.13.0"
dependencies:
  - name: argo-cd
    version: 7.7.10
    repository: https://argoproj.github.io/argo-helm
