---
- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart AdGuardHome
  ansible.builtin.service:
    name: adguardhome
    state: restarted
    enabled: true
