$ANSIBLE_VAULT;1.1;AES256
38623561343062386634366164633435326130336261353331633333383934626438303162353838
3236333664646463386661393638346437343735363839660a613938323261653339646132633234
62393062393235623737666166356266346663356165643931313861643765666537626133383035
3966383966316339390a393361386265626663653137303835323031373563613463656430373665
37616337666366306135323765346234633535656262326465343331346137613761656534663861
37643763613139363637363133633431396233636461666663316231326533626365636262373464
36323262303332653231656362356234313932663563346234373163393139376632383864623533
37663064343063616337346131386365383737383739353362666164383931306365376133623637
62303762356135643731653766633764313830336438663636376230366134616130303038386134
63383132343239653333613865373764396466656331353732303439356564356636636536333339
33326461613332396438313363346539313832613838303039323362386661663036623665616433
34636239326238336430
