$ANSIBLE_VAULT;1.1;AES256
35306331656236643165393361333437366366363934363461343432366239666538353661393236
3130363239663363636465313138393036393662613130370a393561393635343433386535356436
65636135663930303833336363653064626233373364343330313439646136353538653539336664
3863393763623634620a613433313531636465313039626663393633653836313666363735383263
39386166393062323331623234346534656663616563333433326539383331643165366462316665
30663038393661656464633035323665326133373962633338346130386564663262373463363431
32343938373363356639623166323532356436386132636665303934376234396534616165356661
36623262303837356365303562373763353361333032363731633963376365633361343861316561
64666337656337663436303838386534356132326532366334643530326561356432636230343438
65386665313636333265373062363138643930653038363661653664313265356137643666633564
63316330646230336336326339633236393036323336363635383737643161383861333663653236
61356464653335353761653136643930386539323831393438613632616232653330663232643136
66666664623266303632373761663233626164633261613762363765363433636134363161346435
62626366623435363162613033346330313165383937343531336636333130323034366266393765
39393036323331376134326266356337643038343163653230646231633361306136646636623463
33343765363362323031396563626563393861333764313737373434643334373938353565633062
31346433386239633264343331373230393363393839376435323735626531373835313837333039
34636164343036386635343466343439366635376138653133656464373130393133303462666233
37383364363934396539386334656130343935323830333962376330363437303439373238633334
35326636303163383734366565613234616536363334303865636534336237656538386434356431
34636230313165393738616633353364336439343933303161363136633339633339306465663637
32333934376265303230313936366562393335376564313764313132613838353835323137373233
373865396562303938653139313933663733
