---
# Docker macvlan network configuration
docker_networks:
  - name: traefik_int
    vlan_id: 7
    vlan_device: dummy0.7
    parent_interface: mac0.7
    interface_name: traefik_int
    subnet_ipv4: "192.168.7.0/24"
    gateway_ipv4: "192.168.7.1"
    ip_range_ipv4: "192.168.7.128/25"
    subnet_ipv6: "{{ ula_prefix }}:7::/64"
    netmask: "255.255.255.0"

  - name: traefik_ext
    vlan_id: 8
    vlan_device: dummy0.8
    parent_interface: mac0.8
    interface_name: traefik_ext
    subnet_ipv4: "192.168.8.0/24"
    gateway_ipv4: "192.168.8.1"
    ip_range_ipv4: "192.168.8.128/25"
    subnet_ipv6: "{{ ula_prefix }}:8::/64"
    netmask: "255.255.255.0"
