---
ansible_python_interpreter: /usr/bin/python3.11
ansible_user: root
firmware_version: 24.10.5
# datadrive_mount_dir: /data
docker_data_dir: /data/docker

acme_key: /etc/acme/{{ domain }}_ecc/{{ domain }}.key
acme_cert: /etc/acme/{{ domain }}_ecc/fullchain.cer

# Secrets vars
bbox_mac: "{{ secret_bbox_mac }}"
root_password: "{{ secret_root_password }}"
ssh_key: "{{ secret_ssh_key }}"
domain: "{{ secret_domain }}"
ula_prefix: "{{ secret_ula_prefix }}"

ddns_domain: "{{ secret_ddns_domain }}"
ddns_service_name: "{{ secret_ddns_service_name }}"
ddns_username: "{{ secret_ddns_username }}"
ddns_password: "{{ secret_ddns_password }}"

acme_email: "{{ secret_acme_email }}"
acme_dns: "{{ secret_acme_dns }}"
acme_credentials: "{{ secret_acme_credentials }}"

adguardhome_user: "{{ secret_adguardhome_user }}"
adguardhome_password: "{{ secret_adguardhome_password }}"

crowdsec_firewall_bouncer_api_key: "{{ secret_crowdsec_firewall_bouncer_api_key }}"
crowdsec_enroll_key: "{{ secret_crowdsec_enroll_key }}"

smtp_host: "{{ secret_smtp_host }}"
smtp_username: "{{ secret_smtp_username }}"
smtp_password: "{{ secret_smtp_password }}"

authelia_jwt_secret: "{{ secret_authelia_jwt_secret }}"
authelia_session_secret: "{{ secret_authelia_session_secret }}"
authelia_storage_encryption_key: "{{ secret_authelia_storage_encryption_key }}"
authelia_admin_password: "{{ secret_authelia_admin_password }}"

k3s_token: "{{ secret_k3s_token }}"

vpn_private_key: "{{ secret_vpn_private_key }}"
vpn_preshared_key: "{{ secret_vpn_preshared_key }}"
vpn_peer_public_key: "{{ secret_vpn_peer_public_key }}"
vpn_endpoint_host: "{{ secret_vpn_endpoint_host }}"
