---
ansible_python_interpreter: /usr/bin/python3.11
ansible_user: root
firmware_version: 24.10.5
wan_interface: eth3.100
cigale_subnet_id: 1
lan_subnet_id: 2
guest_subnet_id: 3
iot_subnet_id: 4
docker_subnet_id: 9
acme_staging: 1
ddns_enabled: 1

acme_key: /etc/acme/{{ domain }}_ecc/{{ domain }}.key
acme_cert: /etc/acme/{{ domain }}_ecc/fullchain.cer

# Secrets vars
bbox_mac: "{{ secret_bbox_mac }}"
root_password: "{{ secret_root_password }}"
ssh_key: "{{ secret_ssh_key }}"
domain: "{{ secret_domain }}"
ula_prefix: "{{ secret_ula_prefix }}"

ddns_domain: "{{ secret_ddns_domain }}"
ddns_service_name: "{{ secret_ddns_service_name }}"
ddns_username: "{{ secret_ddns_username }}"
ddns_password: "{{ secret_ddns_password }}"

acme_account_email: "{{ secret_acme_account_email }}"
acme_dns: "{{ secret_acme_dns }}"
acme_credentials: "{{ secret_acme_credentials }}"
acme_application_key: "{{ secret_acme_application_key }}"
acme_application_secret: "{{ secret_acme_application_secret }}"
acme_consumer_key: "{{ secret_acme_consumer_key }}"

adguardhome_user: "{{ secret_adguardhome_user }}"
adguardhome_password: "{{ secret_adguardhome_password }}"

crowdsec_firewall_bouncer_api_key: "{{ secret_crowdsec_firewall_bouncer_api_key }}"
crowdsec_enroll_key: "{{ secret_crowdsec_enroll_key }}"

smtp_host: "{{ secret_smtp_host }}"
smtp_username: "{{ secret_smtp_username }}"
smtp_password: "{{ secret_smtp_password }}"

vpn_private_key: "{{ secret_vpn_private_key }}"
vpn_preshared_key: "{{ secret_vpn_preshared_key }}"
vpn_peer_public_key: "{{ secret_vpn_peer_public_key }}"
vpn_endpoint_host: "{{ secret_vpn_endpoint_host }}"

teleport_token: "{{ secret_teleport_token }}"

docker_registry_username: "{{ secret_docker_registry_username }}"
docker_registry_password: "{{ secret_docker_registry_password }}"
