---
ansible_python_interpreter: /usr/bin/python3.11
ansible_user: root
firmware_version: 24.10.4
# datadrive_mount_dir: /data
docker_data_dir: /data/docker

acme_key: /etc/acme/{{ domain }}_ecc/{{ domain }}.key
acme_cert: /etc/acme/{{ domain }}_ecc/fullchain.cer

# Secrets vars
bbox_mac: "{{ secret_bbox_mac }}"
root_password: "{{ secret_root_password }}"
ssh_key: "{{ secret_ssh_key }}"
domain: "{{ secret_domain }}"
ula_prefix: "{{ secret_ula_prefix }}"

ddns_service_name: "{{ secret_ddns_service_name }}"
ddns_username: "{{ secret_ddns_username }}"
ddns_password: "{{ secret_ddns_password }}"

acme_email: "{{ secret_acme_email }}"
acme_dns: "{{ secret_acme_dns }}"
acme_credentials: "{{ secret_acme_credentials }}"

adguardhome_user: "{{ secret_adguardhome_user }}"
adguardhome_password: "{{ secret_adguardhome_password }}"

crowdsec_firewall_bouncer_api_key: "{{ secret_crowdsec_firewall_bouncer_api_key }}"
crowdsec_enroll_key: "{{ secret_crowdsec_enroll_key }}"
