---
ansible_python_interpreter: /usr/bin/python3.11
ansible_user: root
firmware_version: 24.10.4
# datadrive_mount_dir: /data
docker_data_dir: /data/docker
acme_key: /etc/acme/{{ local_domain }}_ecc/{{ local_domain }}.key
acme_cert: /etc/acme/{{ local_domain }}_ecc/fullchain.cer
