---
firmware_version: 24.10.5
opkg_lists_dir: /tmp/opkg-lists
install_firmware_local_file: >-
  {{ playbook_dir ~
     '/build/openwrt-imagebuilder-' ~
     firmware_version ~ '-x86-64.Linux-x86_64/bin/targets/x86/64/' ~
     'openwrt-' ~ firmware_version ~ '-x86-64-generic-ext4-combined-efi.img.gz' }}
