---
- name: Customize .config file
  ansible.builtin.lineinfile:
    path: "{{ firmware_extracted_dir }}/.config"
    regexp: "^#? *{{ item.split('=')[0] }}(=| |$)"
    line: "{{ item }}"
  loop: "{{ config_parameters }}"

- name: Copy custom files
  ansible.builtin.copy:
    src: "files/"
    dest: "{{ firmware_extracted_dir }}/files"
    mode: u=rw,g=r,o=r

- name: Collect template files from filetree
  ansible.builtin.set_fact:
    firmware_template_files: >-
      {{ query('community.general.filetree', role_path ~ '/templates')
         | selectattr('state', 'eq', 'file')
         | selectattr('path', 'match', '.*\.j2$')
         | list }}

- name: Ensure template directories exist
  ansible.builtin.file:
    path: "{{ firmware_extracted_dir }}/files/{{ item.path | splitext | first | dirname }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  loop: "{{ firmware_template_files }}"

- name: Process all templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: "{{ firmware_extracted_dir }}/files/{{ item.path | splitext | first }}"
    mode: u=rw,g=r,o=r
  loop: "{{ firmware_template_files }}"

- name: Set make image params
  ansible.builtin.set_fact:
    firmware_make_image_params: >
      PROFILE="generic"
      FILES="files"
      PACKAGES="{{ (firmware_packages_to_add + firmware_packages_to_delete | map('regex_replace', '^', '-') | list) | join(' ') }}"

- name: Show firmware_make_image_params vars_files
  ansible.builtin.debug:
    var: firmware_make_image_params

# - name: Pause pour vérification manuelle
#   ansible.builtin.pause:
#     prompt: "Veuillez vérifier l'état de la command Make, puis appuyez sur Entrée"

- name: Make image
  community.general.make:
    chdir: "{{ firmware_extracted_dir }}"
    target: image
    params: "{{ firmware_make_image_params }}"

- name: Set combined EFI image gzip path
  ansible.builtin.set_fact:
    firmware_combined_img_gz: >-
      {{
        [
          firmware_extracted_dir,
          'bin/targets/x86/64',
          'openwrt-' ~ firmware_version ~ '-x86-64-generic-ext4-combined-efi.img.gz'
        ] | join('/')
      }}

- name: Set decompressed and qcow2 paths
  ansible.builtin.set_fact:
    firmware_combined_img: "{{ firmware_combined_img_gz | regex_replace('\\.gz$', '') }}"
    firmware_combined_qcow2: "{{ firmware_combined_img_gz | regex_replace('\\.img.gz$', '') }}.qcow2"

- name: Display paths
  ansible.builtin.debug:
    msg:
      - "Source (gzip): {{ firmware_combined_img_gz }}"
      - "Decompressed: {{ firmware_combined_img }}"
      - "QCOW2 target: {{ firmware_combined_qcow2 }}"

- name: Uncompress combined EFI image while keeping the gzip file
  ansible.builtin.command:
    cmd: gzip -dk "{{ firmware_combined_img_gz }}"
    creates: "{{ firmware_combined_img }}"
  register: gunzip_result
  failed_when: gunzip_result.rc not in [0, 2]

- name: Convert combined EFI image to qcow2
  ansible.builtin.command:
    cmd: qemu-img convert -f raw -O qcow2 "{{ firmware_combined_img }}" "{{ firmware_combined_qcow2 }}"
    creates: "{{ firmware_combined_qcow2 }}"

- name: Resize qcow2 image to 25GB
  ansible.builtin.command:
    cmd: qemu-img resize "{{ firmware_combined_qcow2 }}" 25G
  register: resize_result
  changed_when: "'Image resized' in resize_result.stdout or resize_result.rc == 0"

- name: Display final qcow2 info
  ansible.builtin.command:
    cmd: qemu-img info "{{ firmware_combined_qcow2 }}"
  register: qcow2_info
  changed_when: false

- name: Show qcow2 info
  ansible.builtin.debug:
    var: qcow2_info.stdout_lines
