---
- name: Restart crowdsec
  ansible.builtin.service:
    name: crowdsec
    state: restarted

- name: Restart crowdsec-firewall-bouncer
  ansible.builtin.service:
    name: crowdsec-firewall-bouncer
    state: restarted
