config_parameters:
  - CONFIG_TARGET_ROOTFS_PARTSIZE="256"
  - CONFIG_GRUB_TIMEOUT="2"
  - CONFIG_GRUB_BOOTOPTS="microcode.force_minrev=0"
  - CONFIG_GRUB_IMAGES=n
  - CONFIG_TARGET_ROOTFS_SQUASHFS=n
  - CONFIG_TARGET_ROOTFS_EXT4=y
