$ANSIBLE_VAULT;1.1;AES256
39323561613863646232336637333836376462396431323766333162373739333862303330303931
6438336534666265663761363032323131653532393431650a373239623231666531646235636266
66376530316235626539333831626362373965633964376534353633636466663662353863396539
3766353031333062370a653737623164303766636133363731663634383066346439343133373836
35646636663134323130383339653332373531633466363836336639616665303062636135346465
64353662323838373565666638313339313564656439343263366666623838616438336333383737
31303863343663643663666335643661643736653432343933316336366237613561626333363130
37343334303734373633323432666136306235373161396164653261373136393438333731353937
66313930353663646662343333626134653464663735636266373733323833323230316337333338
37336532303833353334643066643262656638326538643335373130613638653839373935343935
62653466343963363234313936613463653031356362663337616664303639333762353735346431
34666130336136393962
