$ANSIBLE_VAULT;1.1;AES256
65303937636231626338343731306563616236666363626639393732326463316132346133316666
6437636637623464333963313238376433393062353937330a373437373230633366333630346334
62396632346562333534616262613836306339393532396335393536613663623338373437613936
3337383064386138300a386361646466386663643761623065376162383539326336383464643439
33303263343833616466343662303834363365663731346262616533316364626331366366323565
33333462363831653934363366366532623133613730333530303763333238376161626565643964
61323039333437393938303165626663663639333439646562383464303936303837363266643164
66613238646139383762323136323131353431373238373131623265663134346461653531356333
36636438653432653533336161356438363237333466373638353031343263666234356561646533
63643837323164326566383463623037303431633936313365343338653939353164323762356135
30363366356639393834323666386635363561653463363431383231623330386637663230333164
63616532656662613730
