---
- name: Ensure needed docker directories exist
  ansible.builtin.file:
    path: "{{ docker_service_volumes_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Render omada docker-compose file
  ansible.builtin.template:
    src: "{{ compose_template_src }}"
    dest: "{{ docker_data_dir }}/{{ service }}/compose.yml"
    mode: '0644'

- name: Deploy docker compose {{ service }}
  community.docker.docker_compose_v2:
    project_src: "{{ docker_data_dir }}/{{ service }}"
    files:
      - compose.yml
    state: present
    recreate: always
