k3s_url: "https://github.com/k3s-io/k3s/releases/download/v1.34.2%2Bk3s1/k3s"
helm_url: "https://get.helm.sh/helm-v4.0.1-linux-amd64.tar.gz"
k3s_admin_subnet_id: 4
k3s_external_subnet_id: 5
k3s_token: "TLtRdxiiCtrm1VDL9xEJCWPGn9ETpwXKzsxfewlAC3U="
# Authelia secrets (générer avec openssl rand -base64 32)
authelia_jwt_secret: "CHANGEME_BASE64_32_CHARS"
authelia_session_secret: "CHANGEME_BASE64_32_CHARS"
authelia_storage_encryption_key: "CHANGEME_BASE64_32_CHARS"

# Hash Argon2 du mot de passe admin (générer avec: docker run --rm authelia/authelia:latest authelia crypto hash generate argon2)
authelia_admin_password: "$argon2id$v=19$m=65536,t=3,p=4$CHANGEME"
