---
- name: Add firewall rule to allow Omada controller to reach EAP
  uci:
    command: section
    config: firewall
    type: rule
    find-by:
      name: Omada to eap
    value:
      src: omada
      dest: lan
      dest_ip:
        - 192.168.1.90
      target: ACCEPT

- name: Commit firewall
  uci:
    command: commit
    config: firewall
  notify: Reload config
