---
- name: Resize root filesystem to fill the data partition
  ansible.builtin.include_tasks: 01_resize_rootfs.yml

- name: Mount data partition to /datadrive
  ansible.builtin.include_tasks: 02_mount_datadrive.yml

- name: Configure DDNS service
  ansible.builtin.include_tasks: 03_ddns.yml

- name: Configure ACME service
  ansible.builtin.include_tasks: 04_acme.yml

- name: Configure SQM service
  ansible.builtin.include_tasks: 05_sqm.yml

- name: Configure DNS proxy service
  ansible.builtin.include_tasks: 06_dns_proxy.yml

- name: Add kernel command line arguments
  ansible.builtin.include_tasks: 07_kernel_cmdline.yml

- name: Configure Docker service
  ansible.builtin.include_tasks: 08_docker.yml
