---
- name: Creates build dir
  ansible.builtin.file:
    path: "{{ firmware_build_dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Set OpenWRT download url
  ansible.builtin.set_fact:
    # https://downloads.openwrt.org/releases/24.10.4/targets/x86/64/
    firmware_download_url: >-
      https://downloads.openwrt.org/releases/{{ firmware_version }}/targets/x86/64/

- name: Set imagebuilder url
  ansible.builtin.set_fact:
    # https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst
    # https://downloads.openwrt.org/releases/22.03.4/targets/x86/64/openwrt-imagebuilder-22.03.4-x86-64.Linux-x86_64.tar.zst
    firmware_imagebuilder_url: >-
      {{ firmware_download_url }}openwrt-imagebuilder-{{ firmware_version }}-x86-64.Linux-x86_64.tar.zst

- name: Set imagebuilder archive filename
  ansible.builtin.set_fact:
    # openwrt-imagebuilder-22.03.4-x86-64.Linux-x86_64.tar.zst
    firmware_imagebuilder_archive: "{{ firmware_imagebuilder_url | basename }}"

- name: Set imagebuilder uncompressed archive dirname
  ansible.builtin.set_fact:
    # openwrt-imagebuilder-22.03.4-x86-64.Linux-x86_64
    firmware_dirname: "{{ firmware_imagebuilder_archive | splitext | first | splitext | first }}"

- name: Set working dir
  ansible.builtin.set_fact:
    # /tmp/openwrt-imagebuilder-22.03.4-x86-64.Linux-x86_64
    firmware_extracted_dir: "{{ firmware_build_dir + firmware_dirname }}"

- name: Download sha256sums file
  ansible.builtin.get_url:
    url: "{{ firmware_download_url }}sha256sums"
    dest: "{{ firmware_build_dir }}sha256sums"
    mode: u=rw,g=r,o=r
    force: true

- name: Set imagebuilder archive sha256
  ansible.builtin.set_fact:
    firmware_imagebuilder_checksum: >-
      {{ 'sha256:' +
        (
          lookup('file', firmware_build_dir + 'sha256sums') |
          regex_search('([a-zA-Z0-9]+) \*' + firmware_imagebuilder_archive.replace('.', '\.'), '\1') |
          first
        )
      }}

- name: Download imagebuilder
  ansible.builtin.get_url:
    url: "{{ firmware_imagebuilder_url }}"
    dest: "{{ firmware_build_dir + firmware_imagebuilder_archive }}"
    checksum: "{{ firmware_imagebuilder_checksum }}"
    mode: u=rw,g=r,o=r

- name: Delete extracted imagebuilder
  ansible.builtin.file:
    path: "{{ firmware_extracted_dir }}"
    state: absent

- name: Unarchive imagebuilder
  ansible.builtin.unarchive:
    src: "{{ firmware_build_dir + firmware_imagebuilder_archive }}"
    dest: "{{ firmware_build_dir }}"
    creates: "{{ firmware_extracted_dir }}"
    remote_src: true
